//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huruf.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscussionComment
    {
        public int DiscusssionCommentID { get; set; }
        public int DiscusssionID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int CommentBy { get; set; }
    }
}
